(function(g){var window=this;'use strict';var fsr=async function(r,p,I){r.U=g.AW(p,I)},sW=function(r){r.isActive()||r.start()},Ww=function(r,p){return p?r.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},GbU=function(r){return g.kc(r)||r.X("web_enable_caption_language_preference_stickiness")},oMA=function(r,p){const I=new g.Lf;
I.languageCode=r.languageCode;I.languageName=r.languageName;I.name=r.name;I.displayName=r.displayName;I.kind=r.kind;I.isDefault=!1;I.W=r.W;I.isTranslateable=r.isTranslateable;I.vssId=r.vssId;I.url=r.url;I.translationLanguage=p;r.xtags&&(I.xtags=r.xtags);r.captionId&&(I.captionId=r.captionId);return I},qGu=async function(r,p){r=r+"|"+p;
p=await g.XK();if(!p)throw g.YX("gct");return(await g.e7(p)).get("captions",r)},MDY=function(r,p,I){qGu(r,p).then(S=>{S&&I(S.trackData,new g.Lf(S.metadata))})},Xh=function(r){if(!ZlU.test(r))throw Error("'"+r+"' is not a valid hex color");
r.length==4&&(r=r.replace(kbg,"#$1$1$2$2$3$3"));r=r.toLowerCase();r=parseInt(r.slice(1),16);return[r>>16,r>>8&255,r&255]},cyR=function(){var r={};
let p="suggest_correction"in g.Qp?g.Qp.suggest_correction:"Edit caption";p=p||"";for(let I in r){const S=()=>String(r[I]);
p=p.replace(new RegExp("\\$\\{"+I+"\\}","gi"),S);p=p.replace(new RegExp("\\$"+I,"gi"),S)}return p},OW=function(){return g.C_("yt-player-caption-display-settings")},gMC=function(r,p){let I=g.wP(r.segments,p);
I>=0||I<0&&(-I-1)%2===1||(I=-I-1,I>0&&p-r.segments[I-1]===1&&I<r.segments.length&&r.segments[I]-p===1?(g.BR(r.segments,I),g.BR(r.segments,I-1)):I>0&&p-r.segments[I-1]===1?r.segments[I-1]=p:I<r.segments.length&&r.segments[I]-p===1?r.segments[I]=p:(g.Or(r.segments,I,0,p),g.Or(r.segments,I+1,0,p)))},TDY=function(r){return r.W&&r.W.C?r.W.C+r.player.n7()<r.player.getCurrentTime():!1},KA5=function(r,p){if(r.policy.eb&&r.player.cY()){var I=g.mR(p,r.policy,{});
I.set("pot",r.player.cY());I=I.A_()}else I=g.mR(p,r.policy,{}).A_();const S={format:"RAW",withCredentials:!0};if(r.policy.dM){S.method="POST";const N=p.N;N&&Object.keys(N).length>0?S.postBody=g.Fb(N,g.cg):S.postBody=(0,g.OV)([120,0])}r.C&&(S.responseType="arraybuffer");let a=++r.rM;const B=(0,g.u)();r.U=g.iU(I,S,3,100,-1,N=>{N.errorCode==="net.timeout"&&r.player.T$("capnt",{rn:a++})}).then(N=>{if(r.policy.Rr&&a%100===1){var v=(0,g.u)();
r.player.T$("caprsp",{rn:a,ms:v-B,kb:(N.xhr.responseText.length/1024).toFixed()})}a:{N=N.xhr;r.Cg();if(r.Z){var e=!(r.C?N.response:N.responseText)||N.status>=400;if(v=g.g2t(N)){N=g.mR(r.Z,r.policy,{});r.Z.q0(N,v);KA5(r,r.Z);break a}e?r.player.T$("capfail",{status:N.status}):(g.ZR("fcb_r",(0,g.u)(),r.player.getVideoData()?.iC||""),v=r.Z.iZ[0],e=v.VJ,r.D!=null&&r.J!==e&&(r.C?r.D(N.response,(v.startTime+r.player.n7())*1E3):r.D(N.responseText,(v.startTime+r.player.n7())*1E3),r.J=e))}r.Z=null;r.U=null}}).Aa(N=>
{r.Z=null;
r.U=null;r.player.T$("capfail",{rn:a,status:N.xhr?.status})});
r.Z=p;gMC(r.N,r.Z.iZ[0].VJ)},QPV=function(r,p){return p!=null&&p in r.U.W?r.U.W[p]:null},EMn=function(r,p,I){const S=[];
for(const a in r.U.W){if(!r.U.W.hasOwnProperty(a))continue;const B=r.U.W[a];if(g.u0(B,I||null)){const N=B.info.captionTrack;N&&N.languageCode===p&&S.push(B)}}return S.length?S[0]:null},tDn=function(r,p){const I=[];
for(const a in r.U.W){if(!r.U.W.hasOwnProperty(a))continue;var S=r.U.W[a];if(g.u0(S,p||null)){let B=S.info.id,N=B,v=`.${B}`,e="",C="";if(S=S.info.captionTrack)B=S.languageCode,N=S.displayName,v=S.vssId,e=S.kind,C=S.id;else{{S=B;let b=g.Oga.get(S);b==null&&(b=jPU[S]||jPU[S.replace(/-/g,"_")],g.Oga.set(S,b));S=b}N=S||N}I.push(new g.Lf({id:a,languageCode:B,languageName:N,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:v,kind:e,captionId:C}))}}return I},DkR=function(r,p,I,S){let a=p/360*16;
p>=r&&(r=640,S>I*1.3&&(r=480),a=I/r*16);return a},har=function(r){let p=1+.25*(r.fontSizeIncrement||0);
if(r.offset===0||r.offset===2)p*=.8;return p},xkg=function(r,p){let I="vertical-rl";
r.W.Ir===1&&(I="vertical-lr");g.yV&&(I=I==="vertical-lr"?"tb-lr":"tb-rl");g.tP(p,"-o-writing-mode",I);g.tP(p,"-webkit-writing-mode",I);g.tP(p,"writing-mode",I);g.tP(p,"text-orientation","upright");g.NL(p,"ytp-vertical-caption");r.U.params.J2===3&&(g.tP(p,"text-orientation",""),g.tP(p,"transform","rotate(180deg)"))},zaU=function(r,p){const I={};
var S=p.background?p.background:r.W.m7.background;if(p.backgroundOpacity!=null||p.background){var a=p.backgroundOpacity!=null?p.backgroundOpacity:r.W.m7.backgroundOpacity;S=Xh(S);I.background="rgba("+S[0]+","+S[1]+","+S[2]+","+a+")";r.kE&&(I["box-decoration-break"]="clone",I["border-radius"]=`${r.Xu/8}px`)}if(p.fontSizeIncrement!=null||p.offset!=null)I["font-size"]=`${r.Rk*har(p)}px`;S=1;a=p.color||r.W.m7.color;if(p.color||p.textOpacity!=null)a=Xh(a),S=p.textOpacity==null?r.W.m7.textOpacity:p.textOpacity,
a="rgba("+a[0]+","+a[1]+","+a[2]+","+S+")",I.color=a,I.fill=a;var B=p.charEdgeStyle;B===0&&(B=void 0);if(B){a=`rgba(34, 34, 34, ${S})`;let e=`rgba(204, 204, 204, ${S})`;p.sT&&(e=a=p.sT);const C=r.Rk/16/2,b=Math.max(C,1);var N=Math.max(2*C,1),v=Math.max(3*C,1);const J=Math.max(5*C,1);S=[];switch(B){case 4:for(;v<=J;v+=C)S.push(`${N}px ${N}px ${v}px ${a}`);break;case 1:N=window.devicePixelRatio>=2?.5:1;for(B=b;B<=v;B+=N)S.push(`${B}px ${B}px ${a}`);break;case 2:S.push(`${b}px ${b}px ${e}`);S.push(`-${b}px -${b}px ${a}`);
break;case 3:for(v=0;v<5;v++)S.push(`0 0 ${N}px ${a}`)}I["text-shadow"]=S.join(", ")}a="";switch(p.fontFamily){case 1:a='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:a='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:a='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:a='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:a='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:a=g.fy()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:a='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}a&&(I["font-family"]=a);a=p.offset;a==null&&(a=r.W.m7.offset);switch(a){case 0:I["vertical-align"]="sub";break;case 2:I["vertical-align"]="super"}p.fontFamily===7&&(I["font-variant"]="small-caps");p.bold&&(I["font-weight"]="bold");p.italic&&(I["font-style"]="italic");p.underline&&
(I["text-decoration"]="underline");p.mK&&(I.visibility="hidden");p.Tz===1&&r.N&&(I["text-combine-upright"]="all",I["text-orientation"]="mixed",a=g.Ql||g.mH,r.U.params.J2===3?I.transform=a?"rotate(90deg)":"rotate(180deg)":a&&(I.transform="rotate(-90deg)"));if(p.textEmphasis===1||p.textEmphasis===2||p.textEmphasis===3||p.textEmphasis===4||p.textEmphasis===5)if(g.Ql)I["font-weight"]="bold";else switch(I["text-emphasis-style"]="filled circle",I["text-emphasis-color"]="currentcolor",I["webkit-text-emphasis"]=
"filled circle",p.textEmphasis){case 4:case 3:I["text-emphasis-position"]="under left";I["webkit-text-emphasis-position"]="under left";break;case 5:case 2:I["text-emphasis-position"]="over right",I["webkit-text-emphasis-position"]="over right"}return I},yE=function(r){r=r.split("px");
return r.length>0?(r=Number(r[0]))?r:0:0},lsg=function(r,p,I){r.dM=r.dM||!!I;
const S={};Object.assign(S,r.W.m7);Object.assign(S,I||p.W);Object.assign(S,r.V5.m7);(I=!r.K)&&mkA(r);let a=r.e_&&r.z$&&g.Ya(S,r.z$)?r.e_:uFa(r,S);const B=typeof p.text==="string",N=B?p.text.split("\n"):[p.text];for(let e=0;e<N.length;e++){var v=e>0||!p.append;const C=N[e];v&&!I?(mkA(r),a=uFa(r,S)):v&&I&&(I=!1);C&&(a.appendChild(B?g.eB(C):C),B||C.tagName!=="RUBY"||C.childElementCount!==4||g.Ql||!g.zN(C.children[2],"text-emphasis")||(v=r.N?"padding-right":"padding-top",g.zN(C.children[2],"text-emphasis-position")&&
(v=r.N?"padding-left":"padding-bottom"),g.ii?g.tP(a,v,"1em"):g.tP(a,v,"0.5em")))}r.z$=S;r.e_=a;r.J.push(p)},mkA=function(r){r.K=g.vb("SPAN");
g.tP(r.K,{display:"block"});g.NL(r.K,"caption-visual-line");r.Z.appendChild(r.K)},uFa=function(r,p){const I=g.vb("SPAN");
g.tP(I,{display:"inline-block","white-space":"pre-wrap"});g.tP(I,zaU(r,p));I.classList.add("ytp-caption-segment");r.K.appendChild(I);I.previousElementSibling&&(g.tP(I.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.tP(I,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return I},FAr=function(r,p,I){if(r===255&&p===255||!r&&!p)return{NP:r,
Wg:p,result:0};r=YGa[r];p=YGa[p];if(r&128){var S;if(S=!(p&128))S=p,S=I.Kk()&&I.Wg===S;if(S)return{NP:r,Wg:p,result:1}}else if(p&128&&1<=r&&r<=31)return{NP:r,Wg:p,result:2};return{NP:r,Wg:p,result:3}},P1C=function(r,p,I,S){p===255&&I===255||!p&&!I?(++r.Z===45&&r.reset(),r.N.U.clear(),r.C.U.clear()):(r.Z=0,UkP(r.N,p,I,S))},nMr=function(r,p){r.W.sort((I,S)=>{const a=I.time-S.time;
return a===0?I.order-S.order:a});
for(const I of r.W)r.time=I.time,I.type===0?P1C(r,I.mU,I.Ua,p):I.type===1&&r.U&496&&UkP(r.C,I.mU,I.Ua,p);r.W.length=0},rvA=function(r,p){switch(r){case 0:return AyR[(p&127)-32];
case 1:return HlU[p&15];case 2:return LAR[p&31];case 3:return RaV[p&31]}return 0},d6=function(r,p){if(r.style.type===3){var I=0,S=0,a=r.C.time+0,B="",N="",v=a;
for(var e=1;e<=15;++e){var C=!1;for(var b=S?S:1;b<=32;++b){var J=r.Z[e][b];if(J.W!==0){I===0&&(I=e,S=b);C=String.fromCharCode(J.W);var W=J.timestamp;W<a&&(a=W);J.timestamp=v;N&&(B+=N,N="");B+=C;C=!0}if((J.W===0||b===32)&&C){N="\n";break}else if(S&&!C)break}if(I&&!C)break}B&&p.N(I,S,a,v,B)}else for(S=I=0,B=a=r.C.time+0,N=1;N<=15;++N)for(v="",e=1;e<=32;++e)if(b=r.Z[N][e],J=b.W,J!==0&&(I===0&&(I=N,S=e),C=String.fromCharCode(J),W=b.timestamp,W<=a&&(a=W),v+=C,b.reset()),e===32||J===0)v&&p.N(I,S,a,B,v),
a=B,v="",S=I=0},VE=function(r){return r.Z[r.row][r.U]},w6=function(r,p,I){p>=2&&r.U>1&&(--r.U,VE(r).W=0);
const S=VE(r);S.timestamp=r.C.time+0;S.W=rvA(p,I);r.U<32&&r.U++},po5=function(r,p,I,S){for(let N=0;N<S;N++)for(let v=0;v<=32;v++){var a=r.Z[p+N][v],B=r.Z[I+N][v];
a.W=B.W;a.timestamp=B.timestamp}},fN=function(r,p,I){for(let S=0;S<I;S++)for(let a=0;a<=32;a++)r.Z[p+S][a].reset()},GU=function(r){r.row=r.W>0?r.W:1;
r.U=1;fN(r,0,15)},I7a=function(r){r.style.set(1);
r.W=r.N;r.W.W=0;r.W.style=r.style;r.Z.mode=1<<r.W.N},os=function(r,p,I){const S=r.U;
let a=!1;switch(r.style.get()){case 4:case 1:case 2:r.style.get()===4&&S.W>0||(d6(S,I),GU(r.U),GU(r.N),S.row=15,S.W=p,a=!0)}r.style.set(3);r.W=S;r.W.style=r.style;r.Z.mode=1<<S.N;a?S.U=1:S.W!==p&&(S.W>p?(d6(S,I),fN(S,S.row-S.W,p)):S.row<p&&(p=S.W),S.W=p)},$Fa=function(r){r.style.set(4);
r.W=r.text;r.W.style=r.style;r.Z.mode=1<<r.W.N},UkP=function(r,p,I,S){r.U.update();
p=FAr(p,I,r.U);switch(p.result){case 0:return;case 1:case 2:return}var a=p.NP;p=p.Wg;if(32<=a||!a)r.W.mode&r.W.U&&(I=a,I&128&&(I=127),p&128&&(p=127),r=r.N.W,I&96&&w6(r,0,I),p&96&&w6(r,0,p),I!==0&&p!==0&&r.style.type===3&&d6(r,S));else if(a&16)a:if(!r.U.matches(a,p)&&(I=r.U,I.NP=a,I.Wg=p,I.state=2,I=a&8?r.J:r.Z,r.N=I,r.W.mode=1<<(r.C<<2)+(I.C<<1)+(I.style.type===4?1:0),(r.W.mode|1<<(r.C<<2)+(I.C<<1)+(I.style.type!==4?1:0))&r.W.U))if(p&64){S=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(a&7)<<1|p>>5&1];
r=p&16?((p&14)>>1)*4:0;p=I.W;switch(I.style.get()){case 4:S=p.row;break;case 3:if(S!==p.row){if(S<p.W&&(S=p.W,S===p.row))break;var B=1+p.row-p.W;const N=1+S-p.W;po5(p,N,B,p.W);I=B;a=p.W;N<B?(B=N+a-B,B>0&&(I+=B,a-=B)):(B=B+a-N,B>0&&(a-=B));fN(p,I,a)}}p.row=S;p.U=r+1}else switch(a&7){case 1:switch(p&112){case 32:w6(I.W,0,32);break a;case 48:p===57?(S=I.W,VE(S).W=0,S.U<32&&S.U++):w6(I.W,1,p&15)}break;case 2:p&32&&w6(I.W,2,p&31);break;case 3:p&32&&w6(I.W,3,p&31);break;case 4:case 5:if(32<=p&&p<=47)switch(p){case 32:I7a(I);
break;case 33:S=I.W;S.U>1&&(--S.U,VE(S).W=0);break;case 36:S=I.W;r=VE(S);for(p=0;p<=15;p++)for(I=0;I<=32;I++)if(S.Z[p][I]===r){for(;I<=32;I++)S.Z[p][I].reset();break}break;case 37:os(I,2,S);break;case 38:os(I,3,S);break;case 39:os(I,4,S);break;case 40:w6(I.W,0,32);break;case 41:S=I;S.style.set(2);S.W=S.U;S.W.W=0;S.W.style=S.style;S.Z.mode=1<<S.W.N;break;case 42:S=I;r=S.text;r.W=15;r.style.set(4);GU(r);$Fa(S);break;case 43:$Fa(I);break;case 44:r=I;p=r.U;switch(r.style.get()){case 1:case 2:case 3:d6(p,
S)}fN(p,0,15);break;case 45:b:{p=I;r=p.W;switch(p.style.get()){default:case 2:case 1:break b;case 4:if(r.row<15){++r.row;r.U=1;break b}break;case 3:}r.W<2&&(r.W=2,r.row<r.W&&(r.row=r.W));p=r.row-r.W+1;d6(r,S);po5(r,p,p+1,r.W-1);fN(r,r.row,1)}break;case 46:fN(I.N,0,15);break;case 47:r=I,d6(r.U,S),r.N.updateTime(r.Z.time+0),S=r.N,r.N=r.U,r.U=S,I7a(r)}break;case 7:switch(p){case 33:case 34:case 35:S=I.W,(S.U+=p&3)>32&&(S.U=32)}}},Smn=function(r,p,I,S,a,B,N){var v=B[0];
let e=N[v.getAttribute("p")];if(e.ij===1){var C=B[1],b=B[2];B=B[3];v.getAttribute("t");C.getAttribute("t");b.getAttribute("t");B.getAttribute("t");v.getAttribute("p");C.getAttribute("p");B.getAttribute("p");N=N[b.getAttribute("p")];v=iCP(v.textContent,C.textContent,b.textContent,B.textContent,N);return new qz(r,p,a,I,v,S,e)}switch(e.ij){case 9:case 10:e.textEmphasis=1;break;case 11:e.textEmphasis=2;break;case 12:e.textEmphasis=3;break;case 13:e.textEmphasis=4;break;case 14:e.textEmphasis=5}return new qz(r,
p,a,I,v.textContent||"",S,e)},iCP=function(r,p,I,S,a){var B=g.fy();
const N=B?g.vb("DIV"):g.vb("RUBY"),v=g.vb("SPAN");v.textContent=r;N.appendChild(v);r=B?g.vb("DIV"):g.vb("RP");r.textContent=p;N.appendChild(r);p=B?g.vb("DIV"):g.vb("RT");p.textContent=I;N.appendChild(p);I=a.ij;if(I===10||I===11||I===12||I===13||I===14)if(g.tP(p,"text-emphasis-style","filled circle"),g.tP(p,"text-emphasis-color","currentcolor"),g.tP(p,"webkit-text-emphasis","filled circle"),a.ij===11||a.ij===13)g.tP(p,"webkit-text-emphasis-position","under left"),g.tP(p,"text-emphasis-position","under left");
I=!0;if(a.ij===4||a.ij===7||a.ij===12||a.ij===14)g.tP(N,"ruby-position","over"),g.tP(N,"-webkit-ruby-position","before");else if(a.ij===5||a.ij===6||a.ij===11||a.ij===13)g.tP(N,"ruby-position","under"),g.tP(N,"-webkit-ruby-position","after"),I=!1;a=B?g.vb("DIV"):g.vb("RP");a.textContent=S;N.appendChild(a);B&&(S=I,g.tP(N,{display:"inline-block",position:"relative"}),B=N.firstElementChild.nextElementSibling,g.tP(B,"display","none"),B=B.nextElementSibling,g.tP(B,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.tP(N.lastElementChild,"display","none"),S?(g.tP(N,"padding-top","0.6em"),g.tP(B,"top","0")):(g.tP(N,"padding-bottom","0.6em"),g.tP(B,"bottom","0")));return N},a7g=function(r){const p="_"+Mz++;
return new Ze(0,0x8000000000000,0,p,r)},kZ=function(r,p){r=r.getAttribute(p);
if(r!=null)return Number(r)},cw=function(r,p){r=r.getAttribute(p);
if(r!=null)return r==="1"},g6=function(r,p){r=kZ(r,p);
return r!==void 0?r:null},KN=function(r,p){r=r.getAttribute(p);
if(r!=null)return TU.test(r),r},B1a=function(r,p){const I={},S=p.getAttribute("ws");
Object.assign(I,S?r.Y[S]:r.N);r=g6(p,"mh");r!=null&&(I.Ko=r);r=g6(p,"ju");r!=null&&(I.textAlign=r);r=g6(p,"pd");r!=null&&(I.J2=r);r=g6(p,"sd");r!=null&&(I.Ir=r);r=KN(p,"wfc");r!=null&&(I.windowColor=r);p=kZ(p,"wfo");p!==void 0&&(I.windowOpacity=p/255);return I},N11=function(r,p){const I={},S=p.getAttribute("wp");
S&&Object.assign(I,r.D[S]);r=g6(p,"ap");r!=null&&(I.B3=r);r=kZ(p,"cc");r!=null&&(I.mD=r);r=kZ(p,"ah");r!=null&&(I.oM=r);r=kZ(p,"rc");r!=null&&(I.zl=r);p=kZ(p,"av");p!=null&&(I.hB=p);return I},vH1=function(r,p,I,S){let a={};
Object.assign(a,N11(r,p));Object.assign(a,B1a(r,p));S?g.Ya(a,r.N)?(S=r.C,a=r.N):S="_"+Mz++:S=p.getAttribute("id")||"_"+Mz++;r=kZ(p,"t")+I;p=kZ(p,"d")||0x8000000000000;if(a.J2===2||a.J2===3)I=a.zl,a.zl=a.mD,a.mD=I;return new Ze(r,p,0,S,a)},QE=function(r){r=g.qe(Math.round(r),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-r.length)+r},exC=function(r,p,I,S,a){S===0&&(S=0x8000000000000);
const B={};p.wpWinPosId&&Object.assign(B,r.N.get(p.wpWinPosId));p.wsWinStyleId&&Object.assign(B,r.C.get(p.wsWinStyleId));r=p.rcRowCount;r!==void 0&&(B.zl=r);p=p.ccColCount;p!==void 0&&(B.mD=p);if(B.J2===2||B.J2===3)p=B.zl,B.zl=B.mD,B.mD=p;return new Ze(I,S,0,a,B)},EW=function(r){const p=r.byteOffset;
r.byteOffset+=1;return r.W.getUint8(p)},jW=function(r){const p=r.byteOffset;
r.byteOffset+=4;return r.W.getUint32(p)},JvR=function(r){if(typeof r==="string")return!1;
r=new CWU(r,0);return bC5(r)},bC5=function(r){if(!(r.byteOffset<r.W.byteLength)||jW(r)!==1380139777)return!1;
r.version=EW(r);if(r.version>1)return!1;EW(r);EW(r);EW(r);return!0},squ=function(r,p){if(!p)return"";
r.N&&r.U.params.Ir!==1&&(p*=-1);return`translate${r.N?"X":"Y"}(${p}px)`},WyY=function(r){r.UD=Array.from(r.element.getElementsByClassName("caption-visual-line"));
for(var p=r.U.params.zl,I=0,S=0,a=r.UD.length-1;I<p&&a>-1;){var B=r.UD[a];S+=r.N?B.offsetWidth:B.offsetHeight;I++;a--}r.L=S;p=Math;I=p.max;isNaN(r.wM)&&((S=r.W.mD)?(a=g.vb("SPAN"),g.Xa(a,"\u2013".repeat(S)),g.tP(a,zaU(r,r.W.m7)),r.Z.appendChild(a),r.wM=a.offsetWidth,r.Z.removeChild(a)):r.wM=0);S=r.Z;r.rM=I.call(p,r.wM,r.RP,(r.N?S.offsetHeight:S.offsetWidth)+1)},Xo1=function(r,p){WyY(r);
var I=r.UD.reduce((S,a)=>(r.N?a.offsetWidth:a.offsetHeight)+S,0);
I=r.L-I;if(I!==r.hG){const S=I>0&&r.hG===0,a=I<r.hG;p||isNaN(I)||S||!a||(g.NL(r.element,"ytp-rollup-mode"),r.B(r.element,"transitionend",r.Yu));g.tP(r.Z,"transform",squ(r,I));r.hG=I}WyY(r)},yvV=function(r,p){r.W=(I,S)=>{if(I.info.Z){var a=I;
if(r.fE.length>0){for(a=r.fE.shift();r.fE.length>0;)a=a.J(r.fE.shift());a=a.J(I)}if(a){I=a;try{var B=g.$z(I)*1E3}catch(X){B=I.info.startTime*1E3}try{var N=g.ffF(I)*1E3}catch(X){N=I.info.duration*1E3}if(B<0||N<0)B<0&&(B=I.info.startTime*1E3),N<0&&(N=I.info.duration*1E3);I.info.startTime=B/1E3;I.info.N=B/1E3;I.info.duration=N/1E3;I.info.D=N/1E3;const {formatId:v,VJ:e,startTimeMs:C,durationMs:b}=r.KG(a);B={formatId:v,startTimeMs:C,durationMs:b,rR:e,YY:e};N=OCn(r.SG,B.startTimeMs);const J=(I=N>=0?r.SG[N]:
null)?I.startTimeMs+I.durationMs:0,W=B.startTimeMs+B.durationMs;!I||B.startTimeMs-J>r.U?r.SG.splice(N+1,0,B):(I.durationMs=Math.max(J,W)-I.startTimeMs,I.YY=Math.max(I.YY,B.YY));S(r.SG);B=g.HL(a);S=r.Z;B=B.buffer.slice(B.byteOffset,B.byteLength+B.byteOffset);a=a.info.N;S.iC?S.D==null?g.A8(S.logger,350058965,"Null loaded track meta data at captions data received"):p.II(B,S.D,a*1E3):g.A8(S.logger,350058965,"Null Representation at captions data received")}else g.A8(r.logger,350058965,"Empty slice")}else r.fE.push(I)};
r.V.addEventListener("sabrCaptionsDataLoaded",r.W)},OCn=function(r,p){r=g.wP(r,{startTimeMs:p},(I,S)=>I.startTimeMs-S.startTimeMs);
return r>=0?r:-r-2},dFY=function(r,p){if(!g.zeh(r)||r.W!=null&&g.mq(p,r.W)&&r.W.W.rawcc!=null)return!1;
p=!!r.W&&r.W.isManifestless&&Object.values(r.W.W).some(I=>g.u0(I,"386"));
r=!!r.W&&!r.W.isManifestless&&g.n2K(r.W);return p||r},Vwn=function(r,p,I){const S=[];
for(const a in r.U.W){if(!r.U.W.hasOwnProperty(a))continue;const B=r.U.W[a];if(g.u0(B,I||null)){const N=B.info.captionTrack;N&&N.languageCode===p&&S.push(B)}}return S.length?S[0]:null},woP=function(r,p){const I=[];
for(const a in r.U.W){if(!r.U.W.hasOwnProperty(a))continue;var S=r.U.W[a];if(g.u0(S,p||null)){let B=S.info.id,N=B,v=`.${B}`,e="",C="";if(S=S.info.captionTrack)B=S.languageCode,N=S.displayName,v=S.vssId,e=S.kind,C=S.id;I.push(new g.Lf({id:a,languageCode:B,languageName:N,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:v,kind:e,captionId:C}))}}return I},GuR=function(r){const p=f7C.length;
if(r.byteLength<p)return!1;r=new Uint8Array(r,0,p);for(let I=0;I<p;I++)if(f7C[I]!==r[I])return!1;return!0},tw=function(r){r=r.split(":");
let p=0;for(const I of r)p=p*60+Number(I);return p*1E3},oHR=function(r,p,I,S){S=Object.assign({Ko:0},S);
return new Ze(r,p,I,"_"+Mz++,S)},qmY=function(r,p,I,S,a,B,N,v,e){switch(N.tagName){case "b":v.bold=!0;
break;case "i":v.italic=!0;break;case "u":v.underline=!0}for(let b=0;b<N.childNodes.length;b++){var C=N.childNodes[b];if(C.nodeType===3)C=new qz(p,I,S,a.id,C.nodeValue,B||b>0,g.mV(v)?void 0:v),e.push(C),a.W.push(C);else{const J={};Object.assign(J,v);qmY(r,p,I,S,a,!0,C,J,e)}}},ZCr=function(r,p,I){if(typeof p==="string"||JvR(p))return[{trackData:p,
pf:I}];if(typeof p==="string"&&p.substring(0,6)==="WEBVTT"||typeof p!=="string"&&GuR(p))return[{trackData:p,pf:I}];const S=new DataView(p);if(S.byteLength<=8||S.getUint32(4)!==1718909296)return[];var a=g.ZhT(S);if(r.O$&&a){var B=g.yri(a),N=g.df9(a);a=a.segmentNumber;B&&a&&r.O$.Ha(a,B,N)}r=g.pn(S,1835295092);if(!r||!r.length||!r[0].size)return[];B=[];for(N=0;N<r.length;N++)a=r[N],a=new Uint8Array(p,a.dataOffset,a.size-(a.dataOffset-a.offset)),a=g.kk(a),B.push({trackData:a,pf:I+N*1E3});MwA(S,B,I);return B=
B.filter(v=>!!v.trackData)},cvA=function(r,p,I){r.W||(r.W=new kuC);
r=r.W.Z(p,I);Math.random()<.01&&g.Qb(Error("Deprecated subtitles format in web player: WebVTT"));return r},MwA=function(r,p,I){var S=g.HS(r,0,1836476516);
let a=9E4;S&&(a=g.Lk(S)||9E4);S=0;const B=g.pn(r,1836019558);for(let v=0;v<B.length;v++){var N=B[v];v<p.length&&(N=g.HS(r,N.dataOffset,1953653094))&&(N=g.HS(r,N.dataOffset,1952867444))&&(N=g.rw(N)/a*1E3,v===0&&(S=N),p[v].pf=N-S+I||I*v*1E3)}},gHg=function(r){const p={};
if(r=g.Uh(r))p.lang=r,g.x9t.test(r)&&(p.J2=1);return p},T1R=function(r){const p=!!r.V.LL()?.WI();
return r.Z==="HLS"&&p?!0:r.HI&&p&&r.Z!=="LIVE"&&r.Z!=="SABR_LIVE"},hw=function(r,p,I=!1){const S=De.m7;
r.C={};Object.assign(r.C,De);r.C.m7={};Object.assign(r.C.m7,S);r.J={m7:{}};var a=p.backgroundOverride?r.J:r.C,B=p.background||S.background;TU.test(B);a.m7.background=B;a=p.colorOverride?r.J:r.C;B=p.color||S.color;TU.test(B);a.m7.color=B;a=p.windowColorOverride?r.J:r.C;B=p.windowColor||De.windowColor;TU.test(B);a.windowColor=B;a=p.backgroundOpacityOverride?r.J:r.C;B=p.backgroundOpacity;B==null&&(B=S.backgroundOpacity);a.m7.backgroundOpacity=B;a=p.fontSizeIncrementOverride?r.J:r.C;B=p.fontSizeIncrement;
B==null&&(B=S.fontSizeIncrement);a.m7.fontSizeIncrement=B;B=p.fontStyleOverride?r.J:r.C;a=p.fontStyle;a==null&&(a=S.bold&&S.italic?3:S.bold?1:S.italic?2:0);B=B.m7;switch(a){case 1:B.bold=!0;delete B.italic;break;case 2:delete B.bold;B.italic=!0;break;case 3:B.bold=!0;B.italic=!0;break;default:delete B.bold,delete B.italic}a=p.textOpacityOverride?r.J:r.C;B=p.textOpacity;B==null&&(B=S.textOpacity);a.m7.textOpacity=B;a=p.windowOpacityOverride?r.J:r.C;B=p.windowOpacity;B==null&&(B=De.windowOpacity);a.windowOpacity=
B;a=p.charEdgeStyleOverride?r.J:r.C;B=p.charEdgeStyle;B==null&&(B=S.charEdgeStyle);a.m7.charEdgeStyle=B;a=p.fontFamilyOverride?r.J:r.C;B=p.fontFamily;B==null&&(B=S.fontFamily);a.m7.fontFamily=B;r.loaded&&r.sD();I&&g.eh("yt-player-caption-display-settings",p,2592E3)},xZ=function(r,p,I){p&&!r.iC?(p=a7g({J2:0,
lang:"en"}),r.iC=[p,new qz(p.start,p.end-p.start,0,p.id,I??"Captions look like this")],r.player.W0(r.iC)):!p&&r.iC&&(KyP(r,r.iC),r.iC=null)},Qqn=function(r){if(!r.V.isInline())return g.C_("yt-player-sticky-caption")},zU=function(r){let p=void 0;
const I=g.Oe().ED(65);if(g.kc(r.qX)&&I!=null){if(Qqn(r)!=null)return!1;p=!I}return p},EHA=function(r){if(r.qX.bf===1||r.videoData.mL===1||g.Hm(r.videoData,"yt:cc")==="alwayson")return!0;
let p;r.videoData.captionTracks.length&&(p=r.getAudioTrack().U);if(r.qX.bf===2){if(g.kc(r.qX))var I=r.qX.X("enable_player_captions_persistence_state_machine")?r.qX.X("enable_player_captions_persistence_state_machine")?g.C_("yt-player-caption-persistence"):void 0:Qqn(r);else if(r.storage)try{I=r.storage.get("module-enabled")}catch(a){r.storage.remove("module-enabled")}else I=null;if(I!=null)return!!I}I=Ww(r.player.getAudioTrack(),g.kc(r.qX));const S=g.Hm(r.videoData,"yt:cc");if(zU(r)===void 0){if(I===
"CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return S?S==="on":!0;if(I==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return S==="on"}else return S==="on";return p==="ON"||g.Hm(r.videoData,"yt:cc")==="on"},mi=function(r,p=!1){if(r.U&&!p||!r.videoData.captionTracks.length)return!1;
r=r.getAudioTrack();return!!r.W||r.U==="FORCED_ON"},jqR=function(r,p){if(r.U){var I=r.V.LL().wu().textTracks,S=null;
r.Z==="HLS"?S=r.U.getId():S=r.U.toString();for(let B=0;B<I.length;B++){var a=I[B];a.id===S&&(p?a.mode!=="showing"&&(a.mode="showing",a=r.U,r.pY(a,!!a,u9(r)?"g":r.K?"m":"s")):a.mode==="showing"&&(a.mode="disabled"))}}},u9=function(r){const p=l9(r);
return!!p&&r.U===p},twn=function(r,p){if(r.Z==="HLS")return!1;
g.SI(r.videoData)&&(p=!0);p||(p=r.Z==="TTS"?!1:r.Z==="INNERTUBE"?!1:!0);return p||r.qX.X("web_deprecate_always_includes_asr_setting")&&g.kc(r.qX)?!0:!!g.Oe().ED(66)},l9=function(r){return r.Y&&r.Y.W},YZ=function(r,p){if(!r.W)return null;
if(r.Y&&r.Y.N)return r.Y.N;p=twn(r,p);p=g.VF(r.W.W,p);let I=null;if(GbU(r.qX)){var S=r.V.isInline()?void 0:g.C_("yt-player-caption-sticky-language");var a=[S,r.videoData.captionsLanguagePreference,r.qX.captionsLanguagePreference,g.Hm(r.videoData,"yt:cc_default_lang")];let v=!1;for(let e=0;e<a.length;e++){const C=a[e];if(C){v=!0;for(var B=0;B<p.length;B++)if(g.Uh(p[B])===C)return p[B];for(B=0;B<p.length;B++)if(g.Uh(p[B]).split("-")[0]===C.split("-")[0])return p[B]}}if(v&&r.W&&(a=r.W.Y,a.length))for(var N of a)if(N.languageCode===
S){I=N;break}}else for(N=[r.videoData.captionsLanguagePreference,r.qX.captionsLanguagePreference,g.Hm(r.videoData,"yt:cc_default_lang")],S=0;S<N.length;S++)for(a=0;a<p.length;a++)if(g.Uh(p[a])===N[S])return p[a];N=null;r.Y&&r.Y.Z&&(N=r.Y.Z);N||(N=p.find(v=>v.isDefault)||null);
N||(N=p[0]||l9(r));N&&I&&g.Uh(N).split("-")[0]!==I.languageCode.split("-")[0]&&(N=oMA(N,I));return N},Aw=function(r,p,I){r.loaded&&r.unload();
I!=null&&(r.K=I,r.K&&(r.qX.X("enable_player_captions_persistence_state_machine")?Fh(r,!!p):g.kc(r.qX)?UW(r,!!p):Pw(r,!!p)));p!==null||mi(r,!0)||r.pY(p,!!p,r.K?"m":"s");r.U=p;mi(r)&&(r.U=l9(r));nN(r,r.U??void 0);r.load()},Fh=function(r,p){r.qX.X("enable_player_captions_persistence_state_machine")&&g.eh("yt-player-caption-persistence",p,3122064E3)},UW=function(r,p){r.V.isInline()||g.eh("yt-player-sticky-caption",p,2592E3)},Pw=function(r,p){if(r.storage)try{r.storage.set("module-enabled",p)}catch(I){}},
nN=function(r,p){r.qX.X("html5_modify_caption_vss_logging")&&(r.videoData.ov=p)},hxr=function(r,p){var I=r.rM[p.id];
I&&I.U!==p&&(I.dispose(),delete r.rM[p.id],I=null);I||(I=DFC(r,p))&&(r.rM[p.id]=I)},xFC=function(r,p){const I=p.windowId;
r.hG[I]||(r.hG[I]=[]);r.hG[I].push(p)},DFC=function(r,p){const I=zxV(r);
if(!I)return null;var S=r.U?g.Uh(r.U):null;S&&g.x9t.test(S)&&(p.params.J2=1);var a=r.Lg.getPlayerSize();S=a.height*r.L.height;a=a.width*r.L.width;r.qX.playerStyle!=="google-live"||r.C.isDefault||Object.assign(p.params,r.C);switch(p.params.Ko!=null?p.params.Ko:p.W.length>1?1:0){case 1:return new mFP(p,r.C,r.J,I.width,I.height,a,S,r.qX.experiments,r.Rk.bind(r),r.V);case 2:return new u1P(p,r.C,r.J,I.width,I.height,a,S,r.qX.experiments,r.Rk.bind(r),r.V);default:return new Hw(p,r.C,r.J,I.width,I.height,
a,S,r.qX.experiments,r.Rk.bind(r),r.V)}},zxV=function(r){let p=r.Lg.getVideoContentRect(!0).height,I=r.Lg.getVideoContentRect(!0).width;
if(!p||!I)return null;p*=r.L.height;I*=r.L.width;return{width:I,height:p}},KyP=function(r,p){r.player.n8(p);
for(const I of p)g.N5(r.wM,I);sW(r.dM)},l7P=function(r,p){if(!r.W)return{};
if(p){g.mV(p)||r.xN(p.vss_id,"m");if(r.N&&r.Z!=="HLS"||!g.MK(p))return;if(g.mV(p)){Aw(r,null,!0);return}let S;var I=g.VF(r.W.W,!0);for(let a=0;a<I.length;a++){const B=I[a];B.languageCode!==p.languageCode||S&&(B.languageName!==p.languageName||(B.captionId||"")!==(p.captionId||"")||g.Yc(B)!==p.displayName)||(S=p.translationLanguage?oMA(B,p.translationLanguage):B)}r.H8(p.position);!S||S===r.U&&r.loaded||(p=g.Xd(),I=g.Uh(S),p.length&&I===p[p.length-1]||(p.push(I),g.eh("yt-player-caption-language-preferences",
p)),GbU(r.qX)&&!r.V.isInline()&&g.eh("yt-player-caption-sticky-language",I,2592E3),Aw(r,S,!0))}else return r.loaded&&r.U&&!u9(r)?g.Fn(r.U):{};return""};
g.p3.prototype.Ha=g.$9(65,function(r,p,I){this.U.set(r,{a_:p,Pd:I})});
g.I_.prototype.Ha=g.$9(64,function(r,p,I){this.iC.Ha(r,p,I)});
g.mc.prototype.L=g.$9(63,function(){return!1});
g.mc.prototype.N=g.$9(62,function(){});
g.uE.prototype.N=g.$9(61,function(r,p,I){this.Cg();p=this.J(r,p);const S=this.tG.G().X("html5_report_captions_ctmp_qoe"),a=(0,g.u)();this.Z();fsr(this,p,{format:"RAW",onSuccess:B=>{this.U=null;if(S){var N=(B.responseText.length/1024).toFixed();const v=(0,g.u)();this.videoData.T$("capresp",{ms:v-a,kb:N})}N=B.getResponseHeader&&B.getResponseHeader("Content-Length")?Number(B.getResponseHeader("Content-Length")):0;I.II(B.responseText,r,void 0,void 0,N)},
onError:S?B=>{this.videoData.T$("capfail",{status:B?.status??0})}:void 0,
withCredentials:!0})});
g.lE.prototype.N=g.$9(60,function(r,p,I){this.Cg();p=this.J(r,p);this.Z();this.U=g.AW(p,{format:"RAW",onSuccess:S=>{this.U=null;const a=S.getResponseHeader&&S.getResponseHeader("Content-Length")?Number(S.getResponseHeader("Content-Length")):0;I.II(S.responseText,r,void 0,void 0,a)},
withCredentials:!0})});
g.RB.prototype.K=g.$9(59,function(){const r=g.Ha(document,"track",void 0,this.W);for(let p=0;p<r.length;p++)g.s3(r[p])});
g.Ii.prototype.K=g.$9(58,function(){this.mediaElement.K()});
g.RB.prototype.UD=g.$9(57,function(){return!(!this.W.textTracks||!this.W.textTracks.addEventListener)});
g.Ii.prototype.UD=g.$9(56,function(){return this.mediaElement.UD()});
g.RB.prototype.WI=g.$9(55,function(){return!!this.W.textTracks});
g.Ii.prototype.WI=g.$9(54,function(){return this.mediaElement.WI()});
g.RB.prototype.iC=g.$9(53,function(r){for(let p=0;p<r.length;p++)this.W.appendChild(r[p])});
g.Ii.prototype.iC=g.$9(52,function(r){this.mediaElement.iC(r)});
g.XG.prototype.uK=g.$9(40,function(r){return this.app.VH({playerType:void 0}).uK(r)});
g.V4.prototype.uK=g.$9(39,function(r){return this.gM.Y4.uK(r)});
g.Ko.prototype.uK=g.$9(38,function(r){return this.Id().some(p=>p.namespace===r)});
g.HJ.prototype.uK=g.$9(37,function(){return!1});
g.XG.prototype.xN=g.$9(35,function(r,p){this.app.j_().xN(r,p)});
g.V4.prototype.xN=g.$9(34,function(r,p){this.gM.xN(r,p)});
g.kB.prototype.xN=g.$9(33,function(r,p){r=[r,p];g.Uw(this,g.AT(this.provider),"cfi",r)});
g.T$.prototype.xN=g.$9(32,function(r,p){this.qoe&&this.qoe.xN(r,p)});
g.Zw.prototype.xN=g.$9(31,function(r,p){this.AL.xN(r,p)});
g.HJ.prototype.xN=g.$9(30,function(){});
g.XG.prototype.pY=g.$9(29,function(r,p,I){this.app.j_().pY(r,p,I)});
g.V4.prototype.pY=g.$9(28,function(r,p,I){this.gM.pY(r,p,I)});
g.kB.prototype.pY=g.$9(27,function(r,p,I){if(this.dM!==r||this.T5!==p)p=p==="rawcc"?"":p,I=[r,p,this.dM,I],g.Uw(this,g.AT(this.provider),"cfs",I),this.dM=r,this.T5=p});
g.T$.prototype.pY=g.$9(26,function(r,p,I){this.qoe&&this.qoe.pY(r,p,I)});
g.Zw.prototype.pY=g.$9(25,function(r,p,I){this.AL.pY(r,p,I)});
g.HJ.prototype.pY=g.$9(24,function(){});
g.Sj.prototype.eU=g.$9(3,function(r){return(r=this.Z(r))?r.W:0});
g.BJ.prototype.eU=g.$9(2,function(){return 0});
var kbg=/#(.)(.)(.)/,ZlU=/^#(?:[0-9a-f]{3}){1,2}$/i,jPU={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},YmU={en:"English"},FyA=class extends g.mc{constructor(r){super(r);this.U=new Set}C(r){var p=this.tG.LL();if(p&&p.wu()){p=p.wu().textTracks;for(const I of p)I.kind==="subtitles"&&!this.U.has(I.language)&&I.language&&(g.zW(this.W,new g.Lf({languageCode:I.language,languageName:I.language,kind:I.kind,id:I.id,displayName:YmU[I.label]||I.label,vss_id:`.${I.language}`})),this.U.add(I.language))}g.VF(this.W).length>
0&&r.T3()}},UFA=class{constructor(){this.segments=[]}contains(r){r=g.wP(this.segments,r);return r>=0||r<0&&(-r-1)%2===1}length(){return this.segments.length/2}},PWY=class extends g.AQ{constructor(r,p,I,S,a,B){super();this.policy=r;this.player=p;this.pg=I;this.D=S;this.C=a;this.L=B;this.N=new UFA;this.J=-1;this.U=this.Z=this.W=null;this.rM=0;this.K=new g.pa(this.iC,1E3,this);this.events=new g.oM(this);g.Z(this,this.K);g.Z(this,this.events);this.events.B(p,"SEEK_COMPLETE",this.Y);this.Y();this.iC()}mE(){super.mE();
this.U&&this.U.cancel()}Y(){this.seekTo(this.player.getCurrentTime())}seekTo(r){r-=this.player.n7();const p=this.W;this.W=g.lh(this.pg.J(r).iZ);p!==this.W&&this.L&&this.L()}reset(){this.N=new UFA;this.J=-1;this.U&&(this.U.cancel(),this.U=null)}iC(){this.Cg();var r;if(r=this.W!=null)r=this.W,r=r.pg.N(r);if(r&&!this.U&&!(this.W&&this.W.startTime-this.player.getCurrentTime()>30)){r=this.W;r=r.pg.dM(r);const a=r.iZ[0];if(this.player.getVideoData()?.enableServerStitchedDai){var p=this.player.Yf();if(p){var I=
a.pg.info.id;const B=a.VJ;var S=r.iZ[0].N;if(this.policy.dM){if(p=g.aJK(p,S,B,I,3))r.N=p}else if(I=p.Ex(S,B,I,3))if(S=2,p.PY.has(B)?S=0:g.oi(p,B)&&(S=1),p=S,p===0)I&&(r.W=new g.fb(I));else if(p===2){this.K.start();TDY(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.pg.index.AD(a.VJ)?(this.N.contains(r.iZ[0].VJ)||KA5(this,r),this.W=g.lh(r.iZ)):TDY(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()}},nHC=class extends g.mc{constructor(r,p){super(p);this.U=r;this.V=p;this.D=
null;this.iC=!1;this.logger=new g.nn("caps");this.rM=g.mq(this.V,this.U)}N(r,p,I){this.Z();p=QPV(this,r.getId());p||(p=r.languageCode,p=this.U.isManifestless?EMn(this,p,"386"):EMn(this,p));if(p){var S=(p.index.eU(p.index.Oe())-p.index.getStartTime(p.index.Oe()))*1E3,a=new g.Y7K(this.V.G());this.D=new PWY(a,this.V,p,(B,N)=>{I.II(B,r,N,S)},this.rM||g.UI(p.info),()=>{this.D&&this.D.reset();
this.iC=!0})}}L(){const r=this.iC;
this.iC=!1;return r}C(r){var p=this.V.G().X("html5_fallback_if_rawcc_missing");const I=this.U.W.rawcc!=null;if(!this.rM||!I&&p)p=this.U.isManifestless?tDn(this,"386"):tDn(this);else{if(!I){g.A8(this.logger,386248249,"rawcc used but unavailable");return}p=[new g.Lf({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Lf({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const S of p)g.zW(this.W,
S);r.T3()}Z(){this.D&&(this.D.dispose(),this.D=null)}J(){return""}},TU=/^#(?:[0-9a-f]{3}){1,2}$/i;var AvY=["left","right","center","justify"];var Hw=class extends g.H{constructor(r,p,I,S,a,B,N,v,e,C){const b=C.isInline()&&!0,J={};Object.assign(J,p);Object.assign(J,r.params);Object.assign(J,I);const W={};Object.assign(W,p.m7);r.params.m7&&Object.assign(W,r.params.m7);Object.assign(W,I.m7);b&&(J.windowOpacity=.6,W.backgroundOpacity=0);J.m7=W;const X=J.J2===1,d=[{S:"span",O:"captions-text",j:{style:"word-wrap: normal; display: block;"}}],M=v.bC("caption_edit_on_hover")&&C.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
M&&d.unshift({S:"button",O:"caption-edit",j:{tabindex:"0","aria-label":cyR()},A:[{S:"svg",j:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},A:[{S:"path",j:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({S:"div",O:"caption-window",j:{id:`${"caption-window"}-${r.id}`,dir:X?"rtl":"ltr",tabindex:"0",lang:J.lang},A:d});this.J=
[];this.dM=!1;this.U=r;this.z$=this.e_=null;this.wx=B;this.gx=N;this.K=null;this.maxWidth=B*.96;this.maxHeight=N*.96;this.W=J;this.V5=I;this.WI=p;this.Z=this.ZH("captions-text");this.kE=this.Z.style.getPropertyValue("box-decoration-break")!==""||this.Z.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Rk=DkR(S,a,B,N);this.Is=e;M&&(this.C=this.ZH("caption-edit"),this.B(this.C,"click",()=>{this.Is()}));
this.type=0;this.Xu=this.Rk*har(W);this.p7=b;this.BI=v.bC("enable_centered_caption_for_tvfilm_video")&&C.getVideoData().isTvfilmVideo;this.Y=C.G().oP().W.ED(g.RHs);r=new g.fY(this.element,!0);g.Z(this,r);r.subscribe("dragstart",this.AY,this);r.subscribe("dragmove",this.KL,this);r.subscribe("dragend",this.Xl,this);this.QJ=this.Lg=this.T5=this.sD=0;r="";this.W.windowOpacity&&(r=Xh(this.W.windowColor),r="rgba("+r[0]+","+r[1]+","+r[2]+","+this.W.windowOpacity+")");p={"background-color":r,display:this.W.isVisible===
!1?"none":"","text-align":AvY[this.W.textAlign]};this.kE&&(p["border-radius"]=r?`${this.Xu/8}px`:"");(this.N=this.U.params.J2===2||this.U.params.J2===3)&&xkg(this,this.element);g.tP(this.element,p);b&&this.element.parentElement?.style.setProperty("--caption-window-color",r);switch(this.W.B3){case 0:case 1:case 2:g.NL(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.NL(this.element,"ytp-caption-window-bottom")}}AY(r,p){this.Lg=r;this.QJ=p;const I=g.Hb(this.element,this.element.parentElement);
this.sD=r-I.x;this.T5=p-I.y}KL(r,p){if(r!==this.Lg||p!==this.QJ){g.BX(this.element,"ytp-dragging")||g.NL(this.element,"ytp-dragging");var I=g.RA(this.element);r=r-this.sD-.02*this.wx;var S=p-this.T5-.02*this.gx,a=(r+I.width/2)/this.maxWidth*3;a=Math.floor(g.qe(a,0,2));var B=(S+I.height/2)/this.maxHeight*3;B=Math.floor(g.qe(B,0,2));p=a+B*3;r=(r+a/2*I.width)/this.maxWidth;r=g.qe(r,0,1)*100;I=(S+B/2*I.height)/this.maxHeight;I=g.qe(I,0,1)*100;this.U.params.B3=p;this.U.params.hB=I;this.U.params.oM=r;this.U.params.isDefault=
!1;this.W.B3=p;this.W.hB=I;this.W.oM=r;this.W.isDefault=!1;this.WI.B3=p;this.WI.hB=I;this.WI.oM=r;this.WI.isDefault=!1;this.L7()}}Xl(){g.ee(this.element,"ytp-dragging")}L7(){this.D(this.J)}D(r){var p=this.p7?0:Math.min(this.H6(),this.maxWidth),I=this.hL(),S=this.p7;if(S){var a=getComputedStyle(this.Z.parentNode);a=yE(a.borderLeftWidth)+yE(a.borderRightWidth)+yE(a.paddingLeft)+yE(a.paddingRight)}else a=0;const B=a;a="";this.U.params.J2===3&&(a="rotate(180deg)");var N=S?`calc(${"96%"} - ${B}px)`:"96%";
g.tP(this.element,{top:0,left:0,right:"",bottom:"",width:p?`${p}px`:"",height:I?`${I}px`:"","max-width":N,"max-height":N,margin:"",transform:""});this.HI(r);a={transform:a,top:"",left:"",width:p?`${p}px`:"",height:I?`${I}px`:"","max-width":"","max-height":""};N=this.W.B3;var v=this.W.oM;const e=this.W.hB;this.BI&&N!=null&&(v=50,N=Math.floor(N/3)*3+1);v=v*.96+2;switch(N){case 0:case 3:case 6:(S=this.W.m7.fontSizeIncrement)&&S>0&&this.W.J2!==2&&this.W.J2!==3&&(v=Math.max(v/(1+S*2),2));a.left=`${v}%`;
break;case 1:case 4:case 7:a.left=`${v}%`;v=0;this.Y||(v=this.Z.offsetWidth);p||v?(p=p||v+1,a.width=`${p}px`,a["margin-left"]=S?`${p/-2-B/2}px`:`${p/-2}px`):(this.Y&&(a.width="max-content"),a.transform+=" translateX(-50%)");break;case 2:case 5:case 8:a.right=`${100-v}%`}S=e*.96+2;switch(N){case 0:case 1:case 2:a.top=`${S}%`;break;case 3:case 4:case 5:a.top=`${S}%`;S=0;this.Y||(S=this.element.clientHeight);(I=I||S)?(a.height=`${I}px`,a["margin-top"]=`${I/-2}px`):a.transform+=" translateY(-50%)";break;
case 6:case 7:case 8:a.bottom=`${100-S}%`}g.tP(this.element,a);if(this.C){if(this.Y)I=this.Xu;else{if(this.BI&&r.length===0)r=0;else{I=1;for(S=0;S<r.length;S++)a=r[S],typeof a.text==="string"&&(I+=a.text.split("\n").length-1,a.append||S===0||I++);r=I}I=this.BI?r>0?this.Z.offsetHeight/r:0:this.Z.offsetHeight/r}this.C.style.height=`${I}px`;this.C.style.width=`${I}px`;this.element.style.paddingLeft=`${I+5}px`;this.element.style.paddingRight=`${I+5}px`;this.Y||(r=Number(this.element.style.marginLeft.replace("px",
""))-I-5,I=Number(this.element.style.marginRight.replace("px",""))-I-5,this.element.style.marginLeft=`${r}px`,this.element.style.marginRight=`${I}px`)}}HI(r){let p;for(p=0;p<r.length&&r[p]===this.J[p];p++);if(this.dM||this.J.length>p)p=0,this.dM=!1,this.J=[],this.K=this.z$=this.e_=null,g.bi(this.Z);for(;p<r.length;p++)lsg(this,r[p])}H6(){return 0}hL(){return 0}toString(){return super.toString()}};var LyU=class{constructor(){this.Z=this.time=this.mode=this.U=0;this.N=new HCa(this);this.C=new HCa(this);this.W=[];this.clear()}clear(){this.Z=this.time=this.mode=0;this.W=[];this.reset()}reset(){this.mode=0;this.N.reset(0);this.C.reset(1)}},YGa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],RxY=class{constructor(){this.type=0}set(r){this.type=r}get(){return this.type}},rjY=class{constructor(){this.state=this.Wg=this.NP=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}Kk(){return this.state!==0}matches(r,p){return this.Kk()&&r===this.NP&&p===this.Wg}},pIa=class{constructor(){this.timestamp=this.W=0}reset(){this.timestamp=
this.W=0}},LN=class{constructor(r){this.C=r;this.Z=[];this.W=this.U=this.row=0;this.style=new RxY;this.N=0;for(r=0;r<=15;r++){this.Z[r]=[];for(let p=0;p<=32;p++)this.Z[r][p]=new pIa}}updateTime(r){for(let p=1;p<=15;++p)for(let I=1;I<=32;++I)this.Z[p][I].timestamp=r}debugString(){let r="\n";for(let p=1;p<=15;++p){for(let I=1;I<=32;++I){const S=this.Z[p][I];r=S.W===0?r+"_":r+String.fromCharCode(S.W)}r+="\n"}return r}reset(r){for(let p=0;p<=15;p++)for(let I=0;I<=32;I++)this.Z[p][I].reset();this.N=r;
this.W=0;this.U=this.row=1}},AyR=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],HlU=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],LAR=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],RaV=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],Ika=class{constructor(r){this.Z=r;this.C=0;this.style=new RxY;this.J=new LN(this.Z);this.K=new LN(this.Z);this.text=new LN(this.Z);this.U=this.J;this.N=this.K;this.W=this.U}reset(r,p){this.C=p;this.style.set(2);this.U=this.J;this.N=this.K;this.W=this.U;const I=(r<<2)+(p<<1);this.J.reset(I);this.K.reset(I);
this.text.reset((r<<2)+(p<<1)+1)}},HCa=class{constructor(r){this.W=r;this.C=0;this.Z=new Ika(this.W);this.J=new Ika(this.W);this.U=new rjY;this.N=this.Z}reset(r){this.C=r;this.U.clear();this.N=this.Z;this.Z.reset(r,0);this.J.reset(r,1)}};var $_n=class{N(){}};var qz=class extends g.Y0{constructor(r,p,I,S,a,B=!1,N=null){super(r,r+p,{priority:I,namespace:"captions"});this.windowId=S;this.text=a;this.append=B;this.W=N}toString(){return super.toString()}};var Rs=class extends g.AQ{reset(){}};var Ze=class extends g.Y0{constructor(r,p,I,S,a){super(r,r+p,{priority:I,namespace:"captions"});this.id=S;this.params=a;this.W=[]}toString(){return super.toString()}},Mz=0;var iKu=class extends Rs{constructor(r){super();this.N=r;this.pens={};this.D={};this.Y={};this.C="_"+Mz++;this.K={};this.U=this.W=null;this.J=!0}reset(){this.K={};this.U=this.W=null;this.J=!0}Z(r,p){r=r.firstChild;r.getAttribute("format");p=p||0;Number.isFinite(p);r=Array.from(r.childNodes);for(var I of r)if(I.nodeType===1)switch(I.tagName){case "head":var S=I;break;case "body":var a=I}if(S){S=Array.from(S.childNodes);for(var B of S)if(B.nodeType===1)switch(B.tagName){case "pen":I=B.getAttribute("id");
S=this.pens;r={};var N=B.getAttribute("p");N&&Object.assign(r,this.pens[N]);N=cw(B,"b");N!=null&&(r.bold=N);N=cw(B,"i");N!=null&&(r.italic=N);N=cw(B,"u");N!=null&&(r.underline=N);N=g6(B,"et");N!=null&&(r.charEdgeStyle=N);N=g6(B,"of");N!=null&&(r.offset=N);N=KN(B,"bc");N!=null&&(r.background=N);N=KN(B,"ec");N!=null&&(r.sT=N);N=KN(B,"fc");N!=null&&(r.color=N);N=g6(B,"fs");N!=null&&N!==0&&(r.fontFamily=N);N=kZ(B,"sz");N!==void 0&&(r.fontSizeIncrement=N/100-1);N=kZ(B,"bo");N!==void 0&&(r.backgroundOpacity=
N/255);N=kZ(B,"fo");N!==void 0&&(r.textOpacity=N/255);N=g6(B,"rb");N!=null&&N!==10&&N!==0&&(r.ij=N>10?N-1:N);N=g6(B,"hg");N!=null&&(r.Tz=N);S[I]=r;break;case "ws":S=B.getAttribute("id");this.Y[S]=B1a(this,B);break;case "wp":S=B.getAttribute("id"),this.D[S]=N11(this,B)}}if(a){B=[];a=Array.from(a.childNodes);for(M of a)if(M.nodeType===1)switch(M.tagName){case "w":this.W=vH1(this,M,p,!1);(a=this.K[this.W.id])&&a.end>this.W.start&&(a.end=this.W.start);this.K[this.W.id]=this.W;B.push(this.W);break;case "p":var v=
M;r=p;a=[];S=v.getAttribute("w")||this.C;I=!!cw(v,"a");r=(kZ(v,"t")||0)+r;N=kZ(v,"d")||5E3;I||(!this.J&&this.U&&this.U.windowId===S&&this.U.end>r&&(this.U.end=r),this.U&&this.U.text==="\n"&&(this.U.text=""));const T=I?6:5;var e=v.getAttribute("p");e=e?this.pens[e]:null;const E=Array.from(v.childNodes);E.length&&(this.J=v.getAttribute("d")!=null);for(v=0;v<E.length;v++){var C=E[v],b=void 0;v>0&&(I=!0);let Q;C.nodeType===1&&(Q=C);if(Q&&Q.tagName==="s"){if((C=(C=Q.getAttribute("p"))?this.pens[C]:null)&&
C.ij&&(C.ij===1?(C=E.slice(v,v+4),C.length===4&&(b=Smn(r,N,S,I,T,C,this.pens),v+=3)):b=Smn(r,N,S,I,T,[Q],this.pens)),!b){var J=Q;b=r;C=N;var W=S,X=I;const D=J.textContent?J.textContent:"";var d=J.getAttribute("p");d=d?this.pens[d]:null;J=kZ(J,"t")||0;b=new qz(b+J,C-J,T,W,D,X,d)}}else b=new qz(r,N,T,S,C.textContent||"",I,e);a.push(b);this.U=b}if(a.length>0){a[0].windowId===this.C&&(this.W=vH1(this,M,p,!0),B.push(this.W));for(const Q of a)Q.windowId=this.W.id,this.W.W.push(Q),B.push(Q)}}var M=B}else M=
[];return M}};var SOa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),akP=class extends Rs{constructor(r){super();this.J=r;this.W=new Map;this.N=new Map;this.C=new Map;this.U=new Map}reset(){this.U.clear()}Z(r,p){r=JSON.parse(r);if(!r)return[];if(r.pens){var I=r.pens,S=0;for(var a of I){I={};var B=a.pParentId;B&&Object.assign(I,this.W.get(B));a.bAttr&&(I.bold=!0);a.iAttr&&(I.italic=!0);a.uAttr&&(I.underline=!0);B=a.ofOffset;B!=null&&(I.offset=B);a.szPenSize!==void 0&&(I.fontSizeIncrement=a.szPenSize/100-1);
B=a.etEdgeType;B!=null&&(I.charEdgeStyle=B);a.ecEdgeColor!==void 0&&(I.sT=QE(a.ecEdgeColor));B=a.fsFontStyle;B!=null&&B!==0&&(I.fontFamily=B);a.fcForeColor!==void 0&&(I.color=QE(a.fcForeColor));a.foForeAlpha!==void 0&&(I.textOpacity=a.foForeAlpha/255);a.bcBackColor!==void 0&&(I.background=QE(a.bcBackColor));a.boBackAlpha!==void 0&&(I.backgroundOpacity=a.boBackAlpha/255);(B=a.rbRuby)&&B!==10&&(I.ij=B>10?B-1:B,I.textEmphasis=SOa.get(I.ij));a.hgHorizGroup&&(I.Tz=a.hgHorizGroup);this.W.set(S++,I)}}if(r.wsWinStyles){S=
r.wsWinStyles;a=0;for(var N of S)S={},(I=N.wsParentId)?Object.assign(S,this.C.get(I)):Object.assign(S,this.J),N.mhModeHint!==void 0&&(S.Ko=N.mhModeHint),N.juJustifCode!==void 0&&(S.textAlign=N.juJustifCode),N.pdPrintDir!==void 0&&(S.J2=N.pdPrintDir),N.sdScrollDir!==void 0&&(S.Ir=N.sdScrollDir),N.wfcWinFillColor!==void 0&&(S.windowColor=QE(N.wfcWinFillColor)),N.wfoWinFillAlpha!==void 0&&(S.windowOpacity=N.wfoWinFillAlpha/255),this.C.set(a++,S)}if(r.wpWinPositions){a=r.wpWinPositions;N=0;for(var v of a)a=
{},(S=v.wpParentId)&&Object.assign(a,this.N.get(S)),v.ahHorPos!==void 0&&(a.oM=v.ahHorPos),v.apPoint!==void 0&&(a.B3=v.apPoint),v.avVerPos!==void 0&&(a.hB=v.avVerPos),v.ccCols!==void 0&&(a.mD=v.ccCols),v.rcRows!==void 0&&(a.zl=v.rcRows),this.N.set(N++,a)}if(r.events){r=r.events;v=[];for(const z of r)if(N=(z.tStartMs||0)+p,a=z.dDurationMs||0,z.id)S=String(z.id),r=exC(this,z,N,a,S),v.push(r),this.U.set(S,r);else{z.wWinId?S=z.wWinId.toString():(S="_"+Mz++,r=exC(this,z,N,a,S),v.push(r),this.U.set(S,r));
r=v;var e=z;a===0&&(a=5E3);I=this.U.get(S);const SF=(B=!!e.aAppend)?6:5,aQ=e.segs;let zB=null;e.pPenId&&(zB=this.W.get(e.pPenId));for(e=0;e<aQ.length;e++){var C=aQ[e],b=C.utf8;if(b){var J=C.tOffsetMs||0;let oQ=null;C.pPenId&&(oQ=this.W.get(C.pPenId));if((I.params.Ko!=null?I.params.Ko:I.W.length>1?1:0)===2&&B&&b==="\n")continue;C=null;var W=[],X;if(X=oQ&&oQ.ij===1)a:{X=aQ;var d=e;if(d+3>=X.length||!X[d+1].pPenId||!X[d+2].pPenId||!X[d+3].pPenId){X=!1;break a}var M=X[d+1].pPenId;(M=this.W.get(M))&&M.ij&&
M.ij===2?(M=X[d+2].pPenId,M=this.W.get(M),!M||!M.ij||M.ij<3?X=!1:(M=X[d+3].pPenId,X=(M=this.W.get(M))&&M.ij&&M.ij===2?!0:!1)):X=!1}if(X)J=aQ[e+1].utf8,C=aQ[e+3].utf8,X=aQ[e+2].utf8,d=this.W.get(aQ[e+2].pPenId),b=iCP(b,J,X,C,d),C=new qz(N,a,SF,S,b,B,oQ),e+=3;else{if(b.indexOf("<")>-1){W=oQ;X=zB;d=N;M=a;var T=J,E=SF,Q=B;const mo=[];var D=g.Gx(`<html>${b}</html>`);if(!D.getElementsByTagName("parsererror").length&&D.firstChild?.childNodes.length)for(const UK of D.firstChild.childNodes){D=UK.textContent?.replace(/\n/g,
"")??"";if(UK.nodeType===3&&(!D||D.match(/^ *$/)!=null))continue;const go={};Object.assign(go,W||X);switch(UK?.tagName){case "b":go.bold=!0;break;case "i":go.italic=!0;break;case "u":go.underline=!0}mo.push(new qz(d+T,M-T,E,I.id,D,Q,go))}W=mo}W.length||(W=[new qz(N+J,a-J,SF,I.id,b,B,oQ||zB)])}if(W.length)for(const mo of W)r.push(mo),I.W.push(mo);else C&&(r.push(C),I.W.push(C))}B=!0}}p=v}else p=[];return p}};var BQr=class extends g.mc{constructor(r,p,I){super(r);this.videoData=p;this.audioTrack=I;this.Y=p.r0}N(r,p,I){MDY(this.videoData.videoId,r.vssId,I.II)}C(r){if(this.audioTrack)for(const p of this.audioTrack.captionTracks)g.zW(this.W,p);r.T3()}};var mFP=class extends Hw{constructor(r,p,I,S,a,B,N,v,e,C){super(r,p,I,S,a,B,N,v,e,C);this.type=1}HI(r){const p=this.U.W;super.HI(r);let I,S;for(r=r.length;r<p.length;r++){const a=p[r];let B;S&&a.W===I?B=S:(B={},Object.assign(B,a.W),Object.assign(B,NQU),I=a.W,S=B);lsg(this,a,B)}}},NQU={mK:!0};var CWU=class extends $_n{constructor(r,p){super();this.trackData=r;this.J=p;this.version=this.C=this.Z=this.byteOffset=0;this.U=[];this.W=new DataView(this.trackData)}N(r,p,I,S,a){if(I<S){const B="_"+Mz++;I=I/1E3-this.J;S=S/1E3-this.J;r=new Ze(I,S-I,5,B,{textAlign:0,B3:0,oM:p*2.5,hB:r*5.33});a=new qz(I,S-I,5,B,a);this.U.push(r);this.U.push(a)}}},vCV=class extends Rs{constructor(r,p){super();this.U=r;this.N=p;this.track=this.N.languageName==="CC3"?4:0;this.W=new LyU;this.W.U=1<<this.track}Z(r){r=
new CWU(r,this.U);if(bC5(r)){for(;r.byteOffset<r.W.byteLength;)for(r.version===0?r.Z=jW(r)*(1E3/45):r.version===1&&(r.Z=jW(r)*4294967296+jW(r)),r.C=EW(r);r.C>0;r.C--){var p=EW(r);const I=EW(r),S=EW(r);p&4&&(p&3)===this.track&&(this.track===0||this.track===1)&&(p=this.W,p.W.push({time:r.Z,type:this.track,mU:I,Ua:S,order:p.W.length}))}nMr(this.W,r);return r.U}return[]}reset(){this.W.clear()}};var u1P=class extends Hw{constructor(r,p,I,S,a,B,N,v,e,C){super(r,p,I,S,a,B,N,v,e,C);this.type=2;this.UD=[];this.rM=this.L=this.hG=0;this.wM=NaN;this.RP=0;this.We=null;this.Dk=new g.pa(this.Yu,433,this);this.C&&(C.createClientVe(this.C,this,167342),this.B(this.C,"click",()=>{C.logClick(this.C)}),r=new g.fY(this.element,!0),g.Z(this,r),r.subscribe("hoverstart",()=>{C.logVisibility(this.C,!0)},this));
g.NL(this.element,"ytp-caption-window-rollup");g.Z(this,this.Dk);g.tP(this.element,"overflow","hidden")}L7(){g.Ih(this.Dk)}Yu(){this.element.removeEventListener("transitionend",this.Yu,!1);g.ee(this.element,"ytp-rollup-mode");this.D(this.We,!0)}hL(){return this.N?this.rM:this.L}H6(){return this.N?this.L:this.rM}D(r,p){this.We=r;if(this.U.params.zl){var I=0;for(let S=0;S<this.J.length&&I<r.length;S++)this.J[S]===r[I]&&I++;I>0&&I<r.length&&(r=this.J.concat(r.slice(I)));this.RP=this.rM;this.L=this.rM=
0;super.D(r);Xo1(this,p)}super.D(r)}};var eFu=class{constructor(r,p,I,S){this.V=r;this.Z=p;this.logger=I;this.C7=S;this.SG=[];this.fE=[];this.W=null;this.s$={h0I:()=>this.W,
ES:()=>this.SG};
r=g.Wt(this.V.G().experiments,"html5_override_micro_discontinuities_threshold_ms");this.U=r>0?r:10}unload(){this.W!=null&&(this.V.removeEventListener("sabrCaptionsDataLoaded",this.W),this.W=null);this.SG=[];this.V.publish("sabrCaptionsBufferedRangesUpdated",this.SG)}KG(r){return{formatId:g.ns(r.info.pg.info,this.C7),VJ:r.info.VJ+(this.C7?0:1),startTimeMs:r.info.N*1E3,durationMs:r.info.D*1E3}}};var CVR=class extends g.mc{constructor(r,p){super(p);this.U=r;this.V=p;this.logger=new g.nn("caps");this.D=this.iC=null;this.rM=new eFu(this.V,this,this.logger,this.U.C7)}N(r,p,I){this.Z();p=r.getId();p=p!=null&&p in this.U.W?this.U.W[p]:null;p||(p=r.languageCode,p=this.U.isManifestless?Vwn(this,p,"386"):Vwn(this,p));p&&(this.D=r,this.iC=p,yvV(this.rM,I),this.V.publish("sabrCaptionsTrackChanged",g.ns(p.info,this.U.C7)))}C(r){var p=this.U.isManifestless?woP(this,"386"):woP(this);for(const I of p)g.zW(this.W,
I);r.T3()}Z(){this.D&&(this.D=this.iC=null,this.rM.unload(),this.V.publish("sabrCaptionsTrackChanged",null))}J(){return""}};var f7C="WEBVTT".split("").map(r=>r.charCodeAt(0)),kuC=class extends Rs{constructor(){super()}Z(r,p){r instanceof ArrayBuffer&&(r=g.kk(new Uint8Array(r)));
const I=[];r=r.split(bKR);for(let d=1;d<r.length;d++){var S=r[d],a=p;if(S!==""&&!Jja.test(S)){var B=rA.exec(S);if(B&&B.length>=4){var N=tw(B[1]),v=tw(B[2])-N;N+=a;var e=(B=B[3])?B.split(" "):[];B={};var C=null;var b="";var J=null,W="";for(const M of e){e=M.split(":");if(e.length!==2)continue;var X=e[1];switch(e[0]){case "line":e=X.split(",");e[0].endsWith("%")&&(C=e[0],B.hB=Number.parseInt(C,10),e.length===2&&(b=e[1].trim()));break;case "position":e=X.split(",");J=e[0];B.oM=Number.parseInt(J,10);
e.length===2&&(W=e[1].trim());break;case "align":switch(X){case "start":B.textAlign=0;break;case "middle":B.textAlign=2;break;case "end":B.textAlign=1}}}C||b||(b="end");if(!J)switch(B.textAlign){case 0:B.oM=0;break;case 1:B.oM=100;break;case 2:B.oM=50}if(B.textAlign!=null){C=0;switch(b){case "center":C+=3;break;case "end":C+=6;break;default:C+=0}switch(W){case "line-left":C+=0;break;case "center":C+=1;break;case "line-right":C+=2;break;default:switch(B.textAlign){case 0:C+=0;break;case 2:C+=1;break;
case 1:C+=2}}b=C<0||C>8?7:C;B.B3=b}S=S.substring(rA.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");W=B;B=S;S={};if(B.indexOf("<")<0&&B.indexOf("&")<0)a=oHR(N,v,5,W),v=new qz(N,v,5,a.id,B,!1,g.mV(S)?void 0:S),I.push(a),I.push(v),a.W.push(v);else for(b=B.split(sFn),b.length===1?(B=5,W=oHR(N,v,B,W)):(C=B=6,W=Object.assign({mD:32},W),W=new Ze(N,v,C,"_"+Mz++,W)),I.push(W),C=N,J=0;J<b.length;J++)if(e=b[J],J%2===0){X=g.Gx(`<html>${e}</html>`);let M;X.getElementsByTagName("parsererror").length?(M=X.createElement("span"),
M.appendChild(X.createTextNode(e))):M=X.firstChild;qmY(this,C,v-(C-N),B,W,J>0,M,S,I)}else C=tw(e)+a}rA.lastIndex=0}}return I}},Jja=/^NOTE/,bKR=/(?:\r\n|\r|\n){2,}/,rA=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),sFn=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var W3R=class extends g.AQ{constructor(r,p){super();this.V=r;this.qX=p;this.W=null;this.O$=this.V.Yf();this.logger=new g.nn("caps")}clear(){this.W&&this.W.dispose();this.W=null}reset(){this.W&&this.W.reset()}mE(){super.mE();this.clear()}};var De={windowColor:"#080808",windowOpacity:0,textAlign:2,B3:7,oM:50,hB:100,isDefault:!0,m7:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.xV("captions",class extends g.z${constructor(r){super(r);this.V=r;this.wM=[];this.rM={};this.hG={};this.K=!1;this.Z="NONE";this.W=this.Y=this.iC=this.z$=this.BI=null;this.QJ={T3:()=>{this.T3()},
II:(S,a,B,N,v=0)=>{const e=Number(this.videoData.G().oP().W.ED(g.N7o)??0);v>0&&e>0&&this.videoData.lengthSeconds>0&&v/this.videoData.lengthSeconds>e?this.V.T$("tts",{dropcap:v}):this.II(S,a,B,N)}};
this.U=null;this.qX=this.V.G();this.videoData=this.V.getVideoData();this.Lg=this.V.qT();this.C={m7:{}};this.J={m7:{}};this.videoData.H6()?this.Z="OFFLINE":g.aDF(this.videoData,this.V)?this.Z="HLS":dFY(this.videoData,this.V)?this.Z="SABR_LIVE":g.B5o(this.videoData,this.V)?this.Z="LIVE":this.videoData.captionTracks.length?this.Z="INNERTUBE":this.videoData.hL&&(this.Z="TTS");this.HI=this.qX.controlsType==="3";this.Xu=new W3R(this.V,this.qX);this.WI=new g.oM(this);this.D=new g.H({S:"div",O:"ytp-caption-window-container",
j:{id:"ytp-caption-window-container"}});this.L={top:0,right:0,bottom:0,left:0,width:1,height:1};let p=null;const I=g.PX("yt-html5-player-modules::subtitlesModuleData");I&&(p=new g.E4(I));this.storage=p;this.Yu=!!r.LL()?.UD();this.N=T1R(this);this.UD=!this.N&&this.HI&&this.Yu&&(this.Z==="LIVE"||this.Z==="SABR_LIVE");g.Z(this,this.Xu);this.N?this.e_=this.dM=null:(this.dM=new g.L6(this.p7,void 0,this),g.Z(this,this.dM),this.e_=new g.pa(this.L7,2E3,this),g.Z(this,this.e_));g.Z(this,this.WI);g.EX(this.player,
this.D.element,4);g.Z(this,this.D);this.N||this.WI.B(r,"resize",this.sD);(this.T5=g.bn(this.qX)&&!g.RX()&&!this.V.isFullscreen()&&!this.N&&!this.UD)&&this.WI.B(r,"resize",this.hL);this.WI.B(r,"onPlaybackAudioChange",this.xE);this.WI.B(r,g.c7("captions"),S=>{this.onCueRangeEnter(S)});
this.WI.B(r,g.g_("captions"),S=>{this.onCueRangeExit(S)});
hw(this,OW()||{});g.y1(this.player,"onCaptionsModuleAvailable");this.Z==="HLS"&&this.N&&(r=this.V.LL().wu(),this.Yu&&this.WI.B(r.textTracks,"addtrack",this.H6))}mE(){if(this.N||this.UD){const r=this.V.LL();r&&!r.Cg()&&r.K()}else xZ(this,!1);super.mE()}kW(){return this.qX.X("html5_honor_caption_availabilities_in_audio_track")&&this.Z!=="LIVE"&&this.Z!=="SABR_LIVE"}yy(){if(this.HI)return this.N||this.UD;if(this.Z==="HLS")return this.N;var r=this.getAudioTrack();if(this.kW()){if(!r.captionTracks.length)return!1;
if(!this.W)return!0}r=Ww(r,g.kc(this.qX));return r==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:r==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?mi(this):zU(this)||mi(this)?!0:EHA(this)}load(){super.load();this.Y=this.getAudioTrack();if(this.W)this.U&&(this.Xu.clear(),this.N?jqR(this,!0):this.player.getPresentingPlayerType()!==3&&this.W.N(this.U,"json3",this.QJ),this.Z!=="HLS"&&this.N||this.UD||u9(this)||g.y1(this.player,"captionschanged",g.Fn(this.U)));else{let r;this.Z==="OFFLINE"?r=new BQr(this.player,this.videoData,
this.getAudioTrack()):this.Z==="SABR_LIVE"?r=new CVR(this.videoData.W,this.player):this.Z==="HLS"?r=new FyA(this.player):this.Z==="LIVE"?r=new nHC(this.videoData.W,this.player):this.Z==="INNERTUBE"?r=new g.uE(this.player,this.videoData,this.getAudioTrack()):r=new g.lE(this.player,this.videoData.hL,this.videoData.videoId,g.l9K(this.videoData),this.videoData.ew,this.videoData.eventId);this.W=r;g.Z(this,this.W);this.W.C(this.QJ)}}unload(){this.N&&this.U?jqR(this,!1):(this.e_&&this.e_.nM(),this.player.Vx("captions"),
this.wM=[],this.W&&this.W.Z(),this.Xu.clear(),this.iC&&this.player.W0(this.iC),this.sD());super.unload();this.player.Dt();g.y1(this.player,"captionschanged",{})}create(){this.yy()&&this.load();var r;a:{if(this.qX.X("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(r=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const p of r)if(p.kind==="asr"&&p.languageCode===
"en"){r=!0;break a}r=!1}r&&this.V.publish("showpromotooltip",this.D.element)}T3(){var r=Ww(this.player.getAudioTrack(),g.kc(this.qX));var p=r==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?YZ(this,this.K):r==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&mi(this)?l9(this):zU(this)||this.K||EHA(this)?YZ(this,this.K):mi(this)?l9(this):null;if(this.Z!=="HLS"&&this.N||this.UD){const I=g.VF(this.W.W,!0);r=[];for(let S=0;S<I.length;S++){const a=I[S],B=g.vb("TRACK");B.setAttribute("kind","subtitles");B.setAttribute("label",
g.Yc(a));B.setAttribute("srclang",g.Uh(a));B.setAttribute("id",a.toString());this.UD||B.setAttribute("src",this.W.J(a,"vtt"));a===p&&B.setAttribute("default","1");r.push(B)}p=this.V.LL();p.iC(r);r=p.wu();this.Yu&&this.WI.B(r.textTracks,"change",this.RP)}else!this.U&&p&&Aw(this,p),g.y1(this.player,"onCaptionsTrackListChanged"),g.ds(this.player,"onApiChange")}getTrackById(r){const p=g.VF(this.W.W,!0);for(let I=0;I<p.length;I++)if(p[I].toString()===r)return p[I];return null}RP(){const r=this.V.LL().wu().textTracks;
let p=null;for(let I=0;I<r.length;I++)r[I].mode==="showing"&&(p=this.getTrackById(r[I].id));(this.loaded?this.U:null)!==p&&Aw(this,p,!0)}H6(){this.W?.C(this.QJ)}Dn(){!this.U&&this.N||this.unload()}II(r,p,I,S){if(r){nN(this,this.U??void 0);this.W.L()&&(this.wM=[],this.V.Vx("captions"),sW(this.dM),this.Xu.reset());a:{var a=this.Xu;S=S||0;I=ZCr(a,r,I||0);r=[];try{for(const E of I){const Q=E.trackData,D=E.pf,z=a.qX.X("safari_live_drm_captions_fix");if(typeof Q!=="string"){I=r;var B=I.concat;if(z&&GuR(Q))var N=
cvA(a,Q,D);else{var v=a,e=p,C=Q,b=D,J=S;if(!JvR(C))throw Error("Invalid binary caption track data");v.W||(v.W=new vCV(J,e));N=v.W.Z(C,b)}var W=B.call(I,N)}else{if(Q.substring(0,6)==="WEBVTT")var X=r.concat(cvA(a,Q,D));else{I=r;var d=I.concat;b:{e=a;v=p;if(Q[0]==="{")try{e.W||(e.W=new akP(gHg(v)));var M=e.W.Z(Q,D);break b}catch(zB){g.Y(zB);M=[];break b}const SF=g.Gx(Q);if(!SF||!SF.firstChild){const zB=Error("Invalid caption track data");zB.params=Q;throw zB;}if(SF.firstChild.tagName==="timedtext"){if(Number(SF.firstChild.getAttribute("format"))===
3){C=SF;e.W||(e.W=new iKu(gHg(v)));M=e.W.Z(C,D);break b}const zB=Error("Unsupported subtitles format in web player (Format2)");zB.params=Q;throw zB;}if(SF.firstChild.tagName==="transcript"){const zB=Error("Unsupported subtitles format in web player (Format1)");zB.params=Q;throw zB;}const aQ=Error("Invalid caption track data");aQ.params=Q;throw aQ;}X=d.call(I,M)}W=X}r=W}var T=r;break a}catch(E){g.A8(a.logger,187101178,`Captions parsing failed: ${E.message}. `);a.clear();T=[];break a}T=void 0}p=T;p.length>
0&&(T=this.U,this.pY(T,!!T,u9(this)?"g":this.K?"m":"s"));this.player.W0(p,void 0,this.Z==="LIVE"||this.Z==="SABR_LIVE");!this.K||this.UD||u9(this)||g.W7(this.qX)||g.Cf(this.qX)||g.Ah(this.qX)||this.qX.rM==="shortspage"||this.player.isInline()||(this.e_.nM(),p=a7g({B3:0,oM:5,hB:5,zl:2,textAlign:0,J2:0,lang:"en"}),this.z$=[p],T=["Click "," for settings"],this.BI||(a=new g.mg(g.k2()),g.Z(this,a),this.BI=a.element),a=p.end-p.start,(W=g.Yc(this.U))&&this.z$.push(new qz(p.start,a,0,p.id,W)),this.z$.push(new qz(p.start,
a,0,p.id,T[0]),new qz(p.start,a,0,p.id,this.BI,!0),new qz(p.start,a,0,p.id,T[1],!0)),this.player.W0(this.z$),this.e_.D9());!this.K||this.UD||u9(this)||(this.qX.X("enable_player_captions_persistence_state_machine")?Fh(this,!0):g.kc(this.qX)?UW(this,!0):Pw(this,!0),this.Y&&(this.Y.N=this.U),this.player.Dt());this.K=!1}}onCueRangeEnter(r){this.wM.push(r);sW(this.dM)}onCueRangeExit(r){g.N5(this.wM,r);this.W instanceof nHC&&this.W.rM&&this.player.n8([r]);sW(this.dM)}getCaptionWindowContainerId(){return this.D.element.id}L7(){KyP(this,
this.z$);this.z$=null}p7(){if(!this.T5||!this.N){this.dM.stop();g.uC(this.hG);this.wM.sort(g.kO);var r=this.wM;if(this.iC){const p=g.Fi(r,function(I){return this.iC.indexOf(I)===-1},this);
p.length&&(r=p)}for(const p of r)p instanceof Ze?hxr(this,p):xFC(this,p);for(const [p,I]of Object.entries(this.rM)){const S=p,a=I;this.hG[S]?(a.element.parentNode||(a instanceof u1P||a instanceof mFP||g.gP(this.rM,(B,N)=>{N!==S&&B.U.params.B3===a.U.params.B3&&B.U.params.oM===a.U.params.oM&&B.U.params.hB===a.U.params.hB&&(B.dispose(),delete this.rM[N]);return N===S},this),this.D.element.appendChild(a.element)),a.D(this.hG[S])):(a.dispose(),delete this.rM[S])}}}Kv(){hw(this,{},!0);
g.y1(this.player,"captionssettingschanged")}GT(){var r=De.m7;r={background:r.background,backgroundOpacity:r.backgroundOpacity,charEdgeStyle:r.charEdgeStyle,color:r.color,fontFamily:r.fontFamily,fontSizeIncrement:r.fontSizeIncrement,fontStyle:r.bold&&r.italic?3:r.bold?1:r.italic?2:0,textOpacity:r.textOpacity,windowColor:De.windowColor,windowOpacity:De.windowOpacity};const p=OW()||{};p.background!=null&&(r.background=p.background);p.backgroundOverride!=null&&(r.backgroundOverride=p.backgroundOverride);
p.backgroundOpacity!=null&&(r.backgroundOpacity=p.backgroundOpacity);p.backgroundOpacityOverride!=null&&(r.backgroundOpacityOverride=p.backgroundOpacityOverride);p.charEdgeStyle!=null&&(r.charEdgeStyle=p.charEdgeStyle);p.charEdgeStyleOverride!=null&&(r.charEdgeStyleOverride=p.charEdgeStyleOverride);p.color!=null&&(r.color=p.color);p.colorOverride!=null&&(r.colorOverride=p.colorOverride);p.fontFamily!=null&&(r.fontFamily=p.fontFamily);p.fontFamilyOverride!=null&&(r.fontFamilyOverride=p.fontFamilyOverride);
p.fontSizeIncrement!=null&&(r.fontSizeIncrement=p.fontSizeIncrement);p.fontSizeIncrementOverride!=null&&(r.fontSizeIncrementOverride=p.fontSizeIncrementOverride);p.fontStyle!=null&&(r.fontStyle=p.fontStyle);p.fontStyleOverride!=null&&(r.fontStyleOverride=p.fontStyleOverride);p.textOpacity!=null&&(r.textOpacity=p.textOpacity);p.textOpacityOverride!=null&&(r.textOpacityOverride=p.textOpacityOverride);p.windowColor!=null&&(r.windowColor=p.windowColor);p.windowColorOverride!=null&&(r.windowColorOverride=
p.windowColorOverride);p.windowOpacity!=null&&(r.windowOpacity=p.windowOpacity);p.windowOpacityOverride!=null&&(r.windowOpacityOverride=p.windowOpacityOverride);return r}kz(r,p){const I={};Object.assign(I,OW());Object.assign(I,r);hw(this,I,p);g.y1(this.player,"captionssettingschanged")}sD(){!this.N&&this.loaded&&(g.ZY(this.rM,function(r,p){r.dispose();delete this.rM[p]},this),this.p7())}kN(r,p){switch(r){case "fontSize":if(isNaN(p))break;
r=g.qe(p,-2,4);this.kz({fontSizeIncrement:r});return r;case "reload":p&&!this.N&&Aw(this,this.U,!0);break;case "stickyLoading":p!==void 0&&this.qX.D&&(this.qX.X("enable_player_captions_persistence_state_machine")?Fh(this,!(!p||!p.userInitiated)):g.kc(this.qX)?UW(this,!!p):Pw(this,!!p));break;case "track":return l7P(this,p);case "tracklist":return this.W?g.P5(g.VF(this.W.W,!(!p||!p.includeAsr)),I=>g.Fn(I)):[];
case "translationLanguages":return this.W?this.W.Y.map(I=>Object.assign({},I)):[];
case "sampleSubtitles":this.N||p===void 0||xZ(this,!!p);break;case "sampleSubtitlesCustomized":this.N||xZ(this,!!p,p);break;case "recommendedTranslationLanguages":return g.Xd();case "defaultTranslationSourceTrackIndices":return this.W?this.W.WI:[]}}getOptions(){const r="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.qX.D&&r.push("stickyLoading");return r}td(){let r=this.U;if(this.V.uK("captions")){if(this.qX.X("html5_modify_caption_vss_logging"))return(r=this.videoData.ov??
null)?{cc:g.Q1K(r)}:{};if(r){let p=r.vssId;r.translationLanguage&&p&&(p=`t${p}.${g.Uh(r)}`);return{cc:p}}}return{}}Cc(){this.isSubtitlesOn()?(this.qX.X("enable_player_captions_persistence_state_machine"),g.kc(this.qX)?UW(this,!1):Pw(this,!1),nN(this),Aw(this,null,!0)):this.C_()}C_(){const r=u9(this)||!this.U?YZ(this,!0):this.U;r&&this.xN(r.vssId,"m");this.isSubtitlesOn()||Aw(this,r,this.qX.X("enable_player_captions_persistence_state_machine")?void 0:!0)}isSubtitlesOn(){return!!this.loaded&&!!this.U&&
!u9(this)}xE(){const r=u9(this);mi(this,r)?Aw(this,this.getAudioTrack().W,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.kW()&&(this.K=!1,this.U=null,this.W&&(this.W.dispose(),this.W=null)),this.yy()&&(r?Aw(this,YZ(this,!1),!1):this.load()))}H8(r){r&&(this.L={top:r.top,right:r.right,bottom:r.bottom,left:r.left,width:1-r.left-r.right,height:1-r.top-r.bottom},this.D.element.style.top=`${this.L.top*100}%`,this.D.element.style.left=`${this.L.left*100}%`,this.D.element.style.width=
`${this.L.width*100}%`,this.D.element.style.height=`${this.L.height*100}%`,this.D.element.style.position="absolute",r=zxV(this))&&(this.D.element.style.width=`${r.width}px`,this.D.element.style.height=`${r.height}px`)}onVideoDataChange(r,p){r==="newdata"&&(this.videoData=p,this.loaded&&this.unload(),this.K=!1,this.U=null,this.W&&(this.W.dispose(),this.W=null,g.y1(this.player,"captionschanged",{})),this.yy()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}hL(){const r=this.V.LL();
r&&!r.Cg()&&r.K();this.V.isFullscreen()?(this.N=this.HI=!0,this.loaded&&this.T3()):(this.HI=this.qX.controlsType==="3",this.N=T1R(this));Aw(this,this.U)}Rk(){const r=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;r&&g.sX(this.player,"innertubeCommand",r)}pY(r,p,I){const S=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let a="";r&&(a=r.vssId,a=a.replace(S,""));let B="";r&&r.getId()&&(B=r.getId()||"");r&&r.getXtags()&&(r=r.getXtags(),r=r.replace(S,""),B=B.concat(`;${r}`));
this.Z==="HLS"&&(B="");this.V.pY(p?a:"",p?B:"",I)}xN(r,p){r=(r||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");r.length>0&&this.V.xN(r,p)}});})(_yt_player);
